// <auto-generated />
using System;
using ALittleLeaf.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ALittleLeaf.Migrations
{
    [DbContext(typeof(AlittleLeafDecorContext))]
    [Migration("20251119151650_AddRefreshTokenTable")]
    partial class AddRefreshTokenTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ALittleLeaf.Models.AddressList", b =>
                {
                    b.Property<int>("AdrsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("adrs_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdrsId"));

                    b.Property<string>("AdrsAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("adrs_address");

                    b.Property<string>("AdrsFullname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("adrs_fullname");

                    b.Property<bool>("AdrsIsDefault")
                        .HasColumnType("bit")
                        .HasColumnName("adrs_isDefault");

                    b.Property<string>("AdrsPhone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("adrs_phone");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long>("IdUser")
                        .HasColumnType("bigint")
                        .HasColumnName("id_user");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("AdrsId")
                        .HasName("PK__Address___3D4B39253A6153A6");

                    b.HasIndex("IdUser");

                    b.ToTable("Address_List", null, t =>
                        {
                            t.HasTrigger("trg_UpdateAddressList");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ALittleLeaf.Models.Bill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("bill_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillId"));

                    b.Property<DateOnly>("DateCreated")
                        .HasColumnType("date")
                        .HasColumnName("date_created");

                    b.Property<int>("IdAdrs")
                        .HasColumnType("int")
                        .HasColumnName("id_adrs");

                    b.Property<long>("IdUser")
                        .HasColumnType("bigint")
                        .HasColumnName("id_user");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("is_confirmed");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("note");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payment_status");

                    b.Property<string>("ShippingStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("shipping_status");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("int")
                        .HasColumnName("total_amount");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("BillId")
                        .HasName("PK__Bill__D706DDB3FB76D27B");

                    b.HasIndex("IdAdrs");

                    b.HasIndex("IdUser");

                    b.ToTable("Bill", null, t =>
                        {
                            t.HasTrigger("trg_UpdateBill");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ALittleLeaf.Models.BillDetail", b =>
                {
                    b.Property<int>("BillDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("bill_detail_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillDetailId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdBill")
                        .HasColumnType("int")
                        .HasColumnName("id_bill");

                    b.Property<int>("IdProduct")
                        .HasColumnType("int")
                        .HasColumnName("id_product");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int")
                        .HasColumnName("total_price");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("int")
                        .HasColumnName("unit_price");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("BillDetailId")
                        .HasName("PK__Bill_Det__3BCDAFBBC3AFB005");

                    b.HasIndex("IdBill");

                    b.HasIndex("IdProduct");

                    b.ToTable("Bill_Detail", null, t =>
                        {
                            t.HasTrigger("trg_UpdateBillDetail");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ALittleLeaf.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryImg")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("category_img");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("category_name");

                    b.Property<int?>("CategoryParentId")
                        .HasColumnType("int")
                        .HasColumnName("category_parent_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("CategoryId")
                        .HasName("PK__Category__D54EE9B4D7980457");

                    b.HasIndex("CategoryParentId");

                    b.ToTable("Category", null, t =>
                        {
                            t.HasTrigger("trg_UpdateCategory");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ALittleLeaf.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdCategory")
                        .HasColumnType("int")
                        .HasColumnName("id_category");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("bit")
                        .HasColumnName("is_onSale");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("product_description");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("product_name");

                    b.Property<int>("ProductPrice")
                        .HasColumnType("int")
                        .HasColumnName("product_price");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int")
                        .HasColumnName("quantity_in_stock");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ProductId")
                        .HasName("PK__Product__47027DF5D9D271A0");

                    b.HasIndex("IdCategory");

                    b.ToTable("Product", null, t =>
                        {
                            t.HasTrigger("trg_UpdateProduct");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ALittleLeaf.Models.ProductImage", b =>
                {
                    b.Property<int>("ImgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("img_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImgId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdProduct")
                        .HasColumnType("int")
                        .HasColumnName("id_product");

                    b.Property<string>("ImgName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("img_name");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit")
                        .HasColumnName("is_primary");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ImgId")
                        .HasName("PK__Product___6F16A71C6F40848C");

                    b.HasIndex("IdProduct");

                    b.ToTable("Product_Images", null, t =>
                        {
                            t.HasTrigger("trg_UpdateProductImages");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ALittleLeaf.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("ALittleLeaf.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("UserBirthday")
                        .HasColumnType("date")
                        .HasColumnName("user_birthday");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("user_email");

                    b.Property<string>("UserFullname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("user_fullname");

                    b.Property<bool>("UserIsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("user_isActive");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("user_password");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("customer")
                        .HasColumnName("user_role");

                    b.Property<bool>("UserSex")
                        .HasColumnType("bit")
                        .HasColumnName("user_sex");

                    b.HasKey("UserId")
                        .HasName("PK__User__B9BE370FE2FFFB58");

                    b.ToTable("User", null, t =>
                        {
                            t.HasTrigger("trg_UpdateUser");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ALittleLeaf.Models.AddressList", b =>
                {
                    b.HasOne("ALittleLeaf.Models.User", "IdUserNavigation")
                        .WithMany("AddressLists")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK__Address_L__id_us__403A8C7D");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("ALittleLeaf.Models.Bill", b =>
                {
                    b.HasOne("ALittleLeaf.Models.AddressList", "IdAdrsNavigation")
                        .WithMany("Bills")
                        .HasForeignKey("IdAdrs")
                        .IsRequired()
                        .HasConstraintName("FK__Bill__id_adrs__45F365D3");

                    b.HasOne("ALittleLeaf.Models.User", "IdUserNavigation")
                        .WithMany("Bills")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK__Bill__updated_at__44FF419A");

                    b.Navigation("IdAdrsNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("ALittleLeaf.Models.BillDetail", b =>
                {
                    b.HasOne("ALittleLeaf.Models.Bill", "IdBillNavigation")
                        .WithMany("BillDetails")
                        .HasForeignKey("IdBill")
                        .IsRequired()
                        .HasConstraintName("FK__Bill_Deta__id_bi__5441852A");

                    b.HasOne("ALittleLeaf.Models.Product", "IdProductNavigation")
                        .WithMany("BillDetails")
                        .HasForeignKey("IdProduct")
                        .IsRequired()
                        .HasConstraintName("FK__Bill_Deta__id_pr__5535A963");

                    b.Navigation("IdBillNavigation");

                    b.Navigation("IdProductNavigation");
                });

            modelBuilder.Entity("ALittleLeaf.Models.Category", b =>
                {
                    b.HasOne("ALittleLeaf.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryParentId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("ALittleLeaf.Models.Product", b =>
                {
                    b.HasOne("ALittleLeaf.Models.Category", "IdCategoryNavigation")
                        .WithMany("Products")
                        .HasForeignKey("IdCategory")
                        .IsRequired()
                        .HasConstraintName("FK__Product__id_cate__4F7CD00D");

                    b.Navigation("IdCategoryNavigation");
                });

            modelBuilder.Entity("ALittleLeaf.Models.ProductImage", b =>
                {
                    b.HasOne("ALittleLeaf.Models.Product", "IdProductNavigation")
                        .WithMany("ProductImages")
                        .HasForeignKey("IdProduct")
                        .IsRequired()
                        .HasConstraintName("FK__Product_I__id_pr__5AEE82B9");

                    b.Navigation("IdProductNavigation");
                });

            modelBuilder.Entity("ALittleLeaf.Models.RefreshToken", b =>
                {
                    b.HasOne("ALittleLeaf.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ALittleLeaf.Models.AddressList", b =>
                {
                    b.Navigation("Bills");
                });

            modelBuilder.Entity("ALittleLeaf.Models.Bill", b =>
                {
                    b.Navigation("BillDetails");
                });

            modelBuilder.Entity("ALittleLeaf.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("ALittleLeaf.Models.Product", b =>
                {
                    b.Navigation("BillDetails");

                    b.Navigation("ProductImages");
                });

            modelBuilder.Entity("ALittleLeaf.Models.User", b =>
                {
                    b.Navigation("AddressLists");

                    b.Navigation("Bills");
                });
#pragma warning restore 612, 618
        }
    }
}
